name: CD Pipeline

on: 
  workflow_dispatch: {}
  push:
    branches:
      # - main
      - devops/cd

jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            include:
              # - context: ./frontend
              #   dockerfile: Dockerfile.prod
              #   tag: peerprep-frontend
              - context: ./backend/question-service
                dockerfile: Dockerfile
                tag: peerprep-question
              - context: ./backend/user-service
                dockerfile: Dockerfile
                tag: peerprep-user
              # - dockerfile: ./backend/matching-service/Dockerfile
              #   tag: peerprep-matching
              # - dockerfile: ./backend/collaboration-service/Dockerfile
              #   tag: peerprep-collab

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Build images
              run: |
                docker build ${{ matrix.context }} -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.tag }}:latest

            - name: Push image to Docker Hub
              run: |
                docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.tag }}:latest

            # - name: Configure AWS credentials
            #   uses: aws-actions/configure-aws-credentials@v4
            #   with:
            #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #     aws-region: ap-southeast-1
            
            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v3
            
            # - name: Login to DockerHub
            #   uses: docker/login-action@v3
            #   with:
            #     username: ${{ secrets.DOCKERHUB_USERNAME }}
            #     password: ${{ secrets.DOCKERHUB_TOKEN }}

            # - name: Extract metadata (tags, labels) for Docker
            #   id: meta
            #   uses: docker/metadata-action@v5
            #   with:
            #     images: ${{ matrix.image }}
            
            # - name: Build and push
            #   uses: docker/build-push-action@v6
            #   with:
            #     context: ${{ matrix.context }}
            #     file: ${{ matrix.dockerfile }}
            #     push: true
            #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.tag }}:latest
            
            # - name: Setup Node.js
            #   uses: actions/setup-node@v4
            #   with:
            #     node-version: '20.x'
            #     cache: 'npm'
            
            # - name: Get Node.js version
            #   run: echo "VERSION=$(node -p 'require("./package.json").version')" >> "$GITHUB_ENV"

            # - name: Generate deployment package
            #   run: zip -r peerprep.zip * -x "**.git**"

            # - name: Deploy to EB
            #   uses: einaregilsson/beanstalk-deploy@v22
            #   with:
            #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #     application_name: PeerPrep
            #     environment_name: PeerPrep-env
            #     version_label: ${{ env.VERSION }}
            #     region: ap-southeast-1
            #     deployment_package: peerprep.zip