name: Backend History Service CI

on:
  workflow_dispatch: {}
  push:
    branches:
      # - main
      - MS6
      - devops/ci

env:
  MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  backend-history-service-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './backend/history-service/package-lock.json'

    # Install dependencies
    - name: Install Backend History Service Dependencies
      working-directory: ./backend/history-service
      run: npm ci

    # Compile code
    - name: Compile Backend History Service Code
      working-directory: ./backend/history-service
      run: npm run build

    # Run history service unit tests
    - name: Run Backend History Service Unit Tests
      working-directory: ./backend/history-service
      run: npm run unit

    # Run history service integration tests
    - name: Run Backend History Service Integration Tests
      working-directory: ./backend/history-service
      run: npm run integration
